version: '3.1'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - spring-cloud-network

  mysql-db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: ozz
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-cloud-network

volumes:
  mysql-data:
    driver: local

networks:
  spring-cloud-network:
    driver: bridge
