version: '3.1'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: ozz
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-cloud-network

  ozz-eureka:
    build: ./eureka
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - spring-cloud-network

  ozz-clothes:
    build: ./clothes
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://ozz-eureka:8761/eureka/
      DB_URL: jdbc:mysql://mysql-db:3306/ozz
      DB_USER: ${DB_USER}
      DB_PW: ${DB_PW}
      SPRING_ELASTICSEARCH_URLS: http://elasticsearch:9200
      SPRING_ELASTICSEARCH_USERNAME: ${SPRING_ELASTICSEARCH_USERNAME}
      SPRING_ELASTICSEARCH_PASSWORD: ${SPRING_ELASTICSEARCH_PASSWORD}
    networks:
      - spring-cloud-network
    depends_on:
      - mysql-db
      - ozz-eureka

  ozz-file:
    build: ./file-server
    ports:
      - "9000:9000"
    volumes:
      - file-data:/data/uploads
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://ozz-eureka:8761/eureka/
      DB_URL: jdbc:mysql://mysql-db:3306/ozz
      DB_USER: ${DB_USER}
      DB_PW: ${DB_PW}
      FILE_UPLOAD_DIR: /data/uploads
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    networks:
      - spring-cloud-network
    depends_on:
      - mysql-db
      - ozz-eureka

  ozz-gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: http://ozz-eureka:8761/eureka/
      ELASTICSEARCH_HOST: http://elasticsearch:9200
    networks:
      - spring-cloud-network
    depends_on:
      - ozz-eureka
      - ozz-file
      - ozz-clothes

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock= true
      - xpack.security.enabled= false
      - xpack.security.enrollment.enabled=false
      - xpack.license.self_generated.type=basic
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - spring-cloud-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.3
    container_name: logstash
    environment:
      - http.host=0.0.0.0
      - http.port=9600
      - xpack.monitoring.enabled=true
      - xpack.monitoring.elasticsearch.hosts=["http://elasticsearch:9200"]
      - path.data=/usr/share/logstash/data
      - DB_USER=${DB_USER}
      - DB_PW=${DB_PW}
    volumes:
      - ./es/logstash/config/:/usr/share/logstash/config/
      - ./es/logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./es/logstash/jars/mysql-connector-java-8.3.0.jar:/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java-8.3.0.jar
    ports:
      - "5044:5044" # Beats input
      - "9600:9600" # Logstash monitoring API
    depends_on:
      - elasticsearch
    networks:
      - spring-cloud-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_UTL : http://elasticsearch:9200
    #      ELASTICSEARCH_USERNAME: ssafy
    #      ELASTICSEARCH_PASSWORD: ssafy1234
    depends_on:
      - elasticsearch
    networks:
      - spring-cloud-network

volumes:
  mysql-data:
    driver: local
  file-data:
    driver: local
  es-data:
    driver: local

networks:
  spring-cloud-network:
    driver: bridge
