version: '3.1'

services:
  ozz-eureka:
    container_name: ozz-eureka
    build: ./eureka
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
