version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.37.6
    container_name: prometheus
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - "7070:7070"
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.listen-address=:7070'  # 포트 설정 추가
    restart: always
    networks:
      - spring-cloud-network

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    ports:
      - "4000:4000"
    volumes:
      - ./grafana/volume:/var/lib/grafana
    environment:
      - GF_SERVER_HTTP_PORT=4000  # 환경 변수 설정
    restart: always
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge
  message-queue-network:
    driver: bridge
