server:
  port: 8081

spring:
  application:
    name: ozz-clothes
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URLS:http://localhost:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:elastic}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:ssafy}
  data:
    elasticsearch:
      repositories:
        enabled: true

logging:
  level:
    root: info