spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
      location: /tmp
  mvc:
    static-path-pattern: /uploads/**
  web:
    resources:
      static-locations: file:${FILE_UPLOAD_DIR}

file:
  upload-dir: ${FILE_UPLOAD_DIR}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}